name = "aiderfixer"
main = "src/index.js"
compatibility_date = "2024-05-01"

# Logging is enabled by default in the Cloudflare dashboard

[vars]
# Define your environment variables here
# APP_ID = "your-github-app-id"
# WEBHOOK_SECRET = "your-webhook-secret"

# Secrets that need to be set using wrangler:
# wrangler secret put PRIVATE_KEY
# wrangler secret put GEMINI_API_KEY
